name: cuidapet_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

dependencies:
  args: ^2.5.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  dotenv: ^4.2.0
  mysql1: ^0.20.0
  get_it: ^7.7.0
  logger: ^2.4.0
  injectable: ^2.4.2

dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.11
  injectable_generator: ^2.6.1
